---
title: "Tutorial 1"
author: "Andrew Chou"
date: "22 August 2021"
output:
  html_document:
    toc: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read arrest.rds

```{r echo = TRUE, results = 'hide'}
arrests <- readRDS("../data/arrests.rds")
```

## Question 1
Fill in two NA values
```{r}
arrests$`2011`$age$Female[1] <- 3109
arrests$`2019`$age$Male[2] <- 2663
```

## Question 2
Print tables
```{r, warning = FALSE}
knitr::kable(
  arrests$`2019`$citizenship,
  caption = "Table 1: Citizenship and Gender",
  row.names = c(0, 0),
  col.names = c("Citizenship status", "Male", "Female"))

knitr::kable(
  arrests$`2019`$age,
  caption = "Table 2: Age and Gender",
  row.names = c(0, 0),
  col.names = c("Age group", "Male", "Female"))
```

## Question 3
Citizenship tables from 2011~2015
```{r}
qn3_list <- list(arrests$`2011`$citizenship,
                 arrests$`2012`$citizenship,
                 arrests$`2013`$citizenship,
                 arrests$`2014`$citizenship,
                 arrests$`2015`$citizenship)
qn3_list
```

## Question 4
Total arrests each year
```{r}
qn4_vec <- sapply(arrests, function(x) sum(x$age[c("Male", "Female")]))
qn4_vec
```

## Question 5
Data of all years with between 17k and 18k arrests
```{r}
satisfy <- (qn4_vec) > 17000 & (qn4_vec) < 18000
qn5_list <- arrests[satisfy]
qn5_list
```

## Question 6
The prop_diff function
```{r}
prop_diff <- function(df) {
  return(df[1, 2] / (df[1, 2] + df[1, 3]) - df[2, 2] / (df[2, 2] + df[2, 3]))
}
qn6_df_1 <- as.data.frame(sapply(arrests, function(x) c(prop_diff(x$citizenship), prop_diff(x$age))))
qn6_df <- as.data.frame(t(qn6_df_1))
names(qn6_df) <- c("citizenship", "age")
qn6_df
```

## Question 7
The log_odds function
```{r}
log_odds <- function(df) {
  return(log(df[1, 2] * df[2, 3] / df[2, 2] / df[1, 3]))
}

qn7_df_1 <- as.data.frame(sapply(arrests, function(x) c(log_odds(x$citizenship), log_odds(x$age))))
qn7_df <- as.data.frame(t(qn7_df_1))
names(qn7_df) <- c("citizenship", "age")
qn7_df
```